# Generated by Django 3.1 on 2020-10-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carreras',
        ),
    ]
