# Generated by Django 3.1 on 2020-10-27 03:22

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_carreras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_carrera', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('titulo_pensum', models.CharField(max_length=50)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('titulo_video', models.CharField(blank=True, max_length=50)),
                ('descripcion_video', models.CharField(max_length=300)),
            ],
        ),
    ]
