# Generated by Django 3.1 on 2020-10-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pensum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensum',
            options={'verbose_name_plural': 'pensums'},
        ),
    ]
