# Generated by Django 3.1 on 2020-11-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201027_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
