# Generated by Django 3.1 on 2020-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201101_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='materia1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia13',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia14',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia15',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia16',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='materia9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
